# Custom Commands
alias bashedit='nano ~/.bashrc'
alias VC='cd; cd Documents/VC'
alias custom='figlet Custom | lolcat; cat ~/Github/dotfiles_custom_commands/.commands | lolcat'
alias custedit='nano ~/Github/dotfiles_custom_commands/.commands'
alias comedit='nano ~/Github/dotfiles_custom_commands/.custom.sh'
alias i3edit='nano ~/.config/i3/config file'
alias dotfiles='cd ~/Github/dotfiles_custom_commands'
alias resolution='arandr'
alias hack='feh --bg-scale ~/Pictures/Wallpaper/hack.jpg'
alias now='timedatectl | lolcat'
alias pi='ssh pi@192.168.8.148'
alias sleep='systemctl suspend'
# Cpu Commands
alias speed='cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_max_freq'
