# Custom Commands
alias bashedit='nano ~/.bashrc'
alias bashedit-c='code ~/.bashrc'
alias zshrcedit='nano ~/.zshrc'
alias zshrcedit-c='code ~/.zshrc'
alias VC='cd; cd Documents/VC'
alias custom='figlet Commands | lolcat; cat ~/Github/dotfiles_pc/.commands | lolcat'
alias custedit='nano ~/Github/dotfiles_pc/.commands'
alias custedit-c='code ~/Github/dotfiles_pc/.commands'
alias comedit='nano ~/Github/dotfiles_pc/.custom.sh'
alias comedit-c='code ~/Github/dotfiles_pc/.custom.sh'
alias i3edit='nano ~/.config/i3/config file'
alias i3edit-c='code ~/.config/i3/config file'
alias dotfiles='cd ~/Github/dotfiles_pc'
alias resolution='arandr'
alias hack='feh --bg-scale ~/Github/dotfiles_pc/hack.jpg'
alias pissh='ssh pi@192.168.8.148'
alias pisftp='sftp pi@192.168.8.148'
alias sleep='systemctl suspend'
alias wakfu='cd;cd Games;./wakfuLauncher.AppImage'
alias eoa='bash ~/Github/dotfiles_pc/EOA.sh'
alias eoa-edit='code ~/Github/dotfiles_pc/EOA.sh'
# Cpu Commands
alias speed='cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_max_freq'
# Resolution Commands
alias resgame='xrandr --output LVDS-1 --mode 960x540'
alias ressupergame='xrandr --output LVDS-1 --mode 640x360'
alias resnormal='xrandr --output LVDS-1 --mode 1366x768'
# API Commands
alias wpe='ruby ~/Github/dotfiles_pc/weather_api.rb 304827 | lolcat'
alias wse='ruby ~/Github/dotfiles_pc/weather_api.rb 297557 | lolcat'
alias woh='ruby ~/Github/dotfiles_pc/weather_api.rb 301205 | lolcat'
alias nyl='ruby ~/Github/dotfiles_pc/weather_api.rb 299069 | lolcat'
alias quote='bash ~/Github/dotfiles_pc/quote_api.sh | lolcat'
